package com.fyber.inneractive.sdk.network;

import cz.msebera.android.httpclient.HttpStatus;

/* loaded from: classes.dex */
public enum o {
    FMP_SDK_INIT_FAILED(62),
    VAST_COMPANION_FAILED_LOADING(70),
    VAST_COMPANION_INCOMPATIBLE_MIMETYPE(75),
    FMP_COMPANION_FAILED_LOADING(78),
    VAST_ERROR_INVALID_RESPONSE(HttpStatus.SC_MOVED_PERMANENTLY),
    VAST_ERROR_TOO_MANY_WRAPPERS(HttpStatus.SC_MOVED_TEMPORARILY),
    VAST_ERROR_NO_MEDIA_FILES(HttpStatus.SC_SEE_OTHER),
    VAST_ERROR_NO_COMPATIBLE_MEDIA_FILE(HttpStatus.SC_NOT_MODIFIED),
    VAST_ERROR_PRE_BUFFER_TIMEOUT(306),
    VAST_ERROR_BUFFER_TIMEOUT(HttpStatus.SC_TEMPORARY_REDIRECT),
    VAST_ERROR_FAILED_PLAYING_MEDIA_FILE(308),
    VAST_ERROR_FAILED_PLAYING_ALL_MEDIA_FILES(311),
    VAST_ERROR_UNSECURE_URL(312),
    MRAID_ERROR_UNSECURE_CONTENT(313),
    VPAID_ERROR_UNSECURE_CONTENT(314),
    MRAID_VIDEO_HAS_NOT_STARTED_PLAYING_IN_A_TIMELY_FASHION(390),
    VAST_UNKNOWN_PLAYER_ERROR(399),
    NATIVE_ERROR_INVALID_NATIVE_RESPONSE(HttpStatus.SC_UNAUTHORIZED),
    NATIVE_ERROR_MISSING_PUB_REQUIRED_FIELD(HttpStatus.SC_PAYMENT_REQUIRED),
    NATIVE_ERROR_MISMATCH_REQUIRED_ASSET_RESPONSE(HttpStatus.SC_NOT_FOUND),
    NATIVE_ERROR_INVALID_REQUIRED_ASSET_DATA(HttpStatus.SC_METHOD_NOT_ALLOWED),
    NATIVE_ERROR_INVALID_OPTIONAL_ASSET_DATA(HttpStatus.SC_NOT_ACCEPTABLE),
    NATIVE_ERROR_INVALID_LINK_WEB_URL(HttpStatus.SC_PROXY_AUTHENTICATION_REQUIRED),
    NATIVE_ERROR_FAILED_LOAD_ASSET(HttpStatus.SC_GONE),
    NATIVE_ERROR_MISMATCH_OPTIONAL_ASSET_RESPONSE(HttpStatus.SC_LENGTH_REQUIRED),
    NATIVE_ERROR_MISSING_PROTOCOL_REQUIRED_FIELD(HttpStatus.SC_PRECONDITION_FAILED),
    NATIVE_ERROR_RECEIVED_VIDEO_BUT_NOT_SUPPORTED(HttpStatus.SC_REQUEST_TOO_LONG),
    NATIVE_ERROR_NO_VALID_URLS_FOR_CLICK(HttpStatus.SC_REQUEST_URI_TOO_LONG),
    NATIVE_ERROR_SOME_INVALID_URLS_FOR_PROCESSED_CLICK(HttpStatus.SC_UNSUPPORTED_MEDIA_TYPE),
    MRAID_AUTO_ACTION_DETECTED(HttpStatus.SC_NOT_IMPLEMENTED),
    INTERNAL_CONFIG_MISMATCH(601),
    FATAL_ADM_PARSING_ERROR(603),
    FATAL_ADM_MARKUP_FETCHING_ERROR(604),
    TOKEN_EXCEEDS_LIMIT(605),
    IGNITE_FLOW_MODE_NOT_COMPATIBLE(606),
    IGNITE_FLOW_FAILED_TO_START(607),
    IGNITE_FLOW_FAILED_TO_INSTALL_APP(612),
    IGNITE_FLOW_FAILED_TO_LOAD_WEBPAGE(613),
    FATAL_CONFIGURATION_ERROR(701),
    FATAL_FEATURES_CONFIG_ERROR(704),
    IA_AD_LOAD_FAILED(801),
    IA_AD_EXPIRED(802),
    IA_AD_DESTROYED_WITHOUT_SHOW(803),
    CLICK_PARSING_FAILURE(991),
    MISSMATCH_SPOTID(992),
    FETCH_TOKEN_DV_ERROR(1000),
    DV_ERROR_PHASE(1001);
    
    public int val;

    o(int i) {
        this.val = i;
    }
}
